/**
 * Created by kanamars on 26/10/19.
 */
export const GET_TRANSACTION_LABELS = 'GET_TRANSACTION_LABELS';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';

export const GET_FILTERS = 'GET_FILTERS';

export const GET_TRANS_DETAILS = 'GET_TRANS_DETAILS';
export const UPDATE_TRANS_DETAILS = 'UPDATE_TRANS_DETAILS';
